"""Re-measure the seam ratio of every finished panorama in a folder of outputs.

    python scripts/measure_seams.py PATH/TO/outputs

Only files named ``<themes>_<MMDD-HHMM>_seed<N>.png`` are final panoramas;
control figures, seam checks and contact sheets are skipped. The ratio is
computed by the notebook's own ``seam_ratio``, loaded from its source, so this
script cannot disagree with the number the notebook printed.

Writes ``results/seam_ratios.csv`` (one row per file) and
``results/seam_ratios.md`` (the summary quoted in the README). Byte-identical
files are reported as reproductions and counted once.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import statistics
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.notebook_code import REPO, load  # noqa: E402

FINAL = re.compile(r"^(?P<themes>.+)_(?P<run>\d{4}-\d{4})_seed(?P<seed>\d+)\.png$")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("outputs", type=Path, help="folder the notebook wrote PNGs into")
    parser.add_argument("--results", type=Path, default=REPO / "results")
    args = parser.parse_args()

    seam_ratio = load("seam_ratio", np=np)["seam_ratio"]

    rows, first_seen = [], {}
    for path in sorted(args.outputs.glob("*.png")):
        match = FINAL.match(path.name)
        if not match:
            continue
        digest = hashlib.md5(path.read_bytes()).hexdigest()
        image = Image.open(path)
        rows.append({
            "themes": match["themes"],
            "run": match["run"],
            "seed": int(match["seed"]),
            "width": image.width,
            "height": image.height,
            "seam_ratio": round(seam_ratio(image), 3),
            "md5": digest,
            "identical_to": first_seen.get(digest, ""),
        })
        first_seen.setdefault(digest, path.name)
    if not rows:
        sys.exit(f"no final panoramas (*_MMDD-HHMM_seedN.png) in {args.outputs}")

    args.results.mkdir(parents=True, exist_ok=True)
    with open(args.results / "seam_ratios.csv", "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    unique = [r for r in rows if not r["identical_to"]]
    duplicates = [r for r in rows if r["identical_to"]]
    ratios = [r["seam_ratio"] for r in unique]
    spread = statistics.stdev(ratios) if len(ratios) > 1 else 0.0
    configs = {(r["themes"], r["run"]) for r in unique}

    lines = [
        "# Seam ratios, re-measured",
        "",
        "Generated by `scripts/measure_seams.py` from the PNGs the notebook wrote.",
        "The seam ratio is `mean|first column - last column| / mean|neighbouring-column",
        "difference|`: about 1 means the wrap-around join is indistinguishable from any",
        "other pair of adjacent columns.",
        "",
        "| | |",
        "|---|---|",
        f"| Panoramas (byte-identical copies counted once) | **{len(unique)}** |",
        f"| Configurations (themes x run) | **{len(configs)}** |",
        f"| Mean seam ratio | **{statistics.mean(ratios):.2f}** |",
        f"| Median / s.d. | {statistics.median(ratios):.2f} / {spread:.2f} |",
        f"| Best / worst | {min(ratios):.2f} / {max(ratios):.2f} |",
        f"| Below 1.5 | {sum(v < 1.5 for v in ratios)} of {len(ratios)} |",
        "",
        "## Reproductions",
        "",
    ]
    if duplicates:
        lines += [
            f"{len(duplicates)} file(s) are byte-identical to an earlier one — the same",
            "seed and settings rendered again in a separate Colab session:",
            "",
            "| File | Identical to | MD5 |",
            "|---|---|---|",
        ]
        lines += [
            f"| `{r['themes']}_{r['run']}_seed{r['seed']}.png` | `{r['identical_to']}` | `{r['md5']}` |"
            for r in duplicates
        ]
    else:
        lines.append("None in this folder.")
    lines += [
        "",
        "## Every panorama",
        "",
        "| Themes | Run | Seed | Size | Seam ratio |",
        "|---|---|---:|---|---:|",
    ]
    lines += [
        f"| {r['themes'].replace('+', ' + ')} | {r['run']} | {r['seed']} | "
        f"{r['width']}x{r['height']} | {r['seam_ratio']:.2f} |"
        for r in unique
    ]
    (args.results / "seam_ratios.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(unique)} panoramas in {len(configs)} configurations, "
          f"{len(duplicates)} byte-identical reproduction(s)")
    print(f"seam ratio mean {statistics.mean(ratios):.3f}  median {statistics.median(ratios):.3f}  "
          f"sd {spread:.3f}  range {min(ratios):.3f}-{max(ratios):.3f}")


if __name__ == "__main__":
    main()
